apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}-service
  labels:
    app: {{ include "name" . }}
spec:
  selector:
    app: {{ include "name" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
