apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "name" . }}-ingress
spec:
  ingressClassName: 
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ printf "%s-frontend-service" .Release.Name }}
            port:
              number: 80
