apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auth-service.name" . }}-db-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: {{ include "auth-service.name" . }}-db-secret
  data:
    - secretKey: DATABASE_USER
      remoteRef:
        key: {{ .Values.environment }}/rds/credentials  
        property: username
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: {{ .Values.environment }}/rds/credentials  
        property: password
  