apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}-service
spec: 
  selector:
    app: {{ include "name" . }}
  ports:    
    - protocol: TCP
      port: 80
      targetPort: 4000
      type: clusterIP

