apiVersion: v1
kind: Deployment
metadata:
  name: {{ include "name" . }}-deployment
  labels:
    app: {{ include "name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "name" . }} 
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
    spec:
      containers:
        - name: {{ include "name" . }}
          image: {{ include "image" . }}