apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "name" . }}
  template:
    metadata:
      labels:
        app: {{ include "name" . }}
    spec:
      containers:
        - name: frontend
          image: {{ include "image" . }}
          ports:
            - containerPort: 80
          env:
            - name: AUTH_SERVICE_URL
              value: "http://{{ .Release.Name }}-auth-service:80"  # Points to auth-service