name: '[ECR] Build & Push Auth Service'
on:
  workflow_dispatch:
   inputs:
      aws-region:
        required: false
        type: string
        default: 'eu-north-1' 

permissions:
      id-token: write
      contents: read

jobs:
  build-and-push-auth-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      - name: Clean and Update Dependencies
        run: |
          cd apps/backend/auth-service
          # Clean current node_modules to force fresh install
          rm -rf node_modules
          # Update ALL packages to latest compatible versions
          npm update --save  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ inputs.aws-region }} 
          role-session-name: GitHubActions-${{ github.run_id }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 1. BUILD with local tag
      - name: Build Auth Service Image
        run: |
          docker build -t auth-service:1.0 ./apps/backend/auth-service

      - name: Debug - Run Trivy with table output
        run: |
          # Install Trivy temporarily for a human-readable report
          wget https://github.com/aquasecurity/trivy/releases/download/v0.68.1/trivy_0.68.1_Linux-64bit.tar.gz
          tar -xzf trivy_0.68.1_Linux-64bit.tar.gz
          ./trivy image --format table --ignore-unfixed auth-service:1.0

      # üîê 2. SECURITY GATE: Scan the image. Job FAILS here if vulnerabilities are found.
      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'auth-service:1.0'
          format: 'sarif'
          exit-code: '1' # This makes the job fail on findings
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      # (Optional) Upload report to GitHub Security tab for visibility
      - name: Upload Trivy Results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
    

      # 3. TAG with full ECR URL
      - name: Tag for ECR
        run: |
          docker tag auth-service:1.0 ${{ steps.login-ecr.outputs.registry }}/devops/auth-service:1.0

      # 4. PUSH to ECR
      - name: Push to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/devops/auth-service:1.0