name: 'Infrastructure'

on: 
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'
  workflow_dispatch:
    inputs:
      infrastructure-action:
        type: choice
        description: "select infrastructure action"
        options:
          - apply
          - destroy
        required: true
jobs: 
  deploy_infra:
    name: Install ubuntu
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: infrastructure

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        if: ${{ github.event.inputs.infrastructure-action == 'apply' }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: ${{ github.event.inputs.infrastructure-action == 'apply' }}
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: ${{ github.event.inputs.infrastructure-action == 'destroy' }}
        run: terraform destroy -auto-approve

